name: buildAuto

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
            cd  SRC
            cd PhoneAgenda
            dotnet restore
    - name: Build
      run: | 
              cd SRC
              cd PhoneAgenda
              dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name build executable
      run |
          cd SRC
          cd PhoneAgenda
          cd PhoneAgendaWebAPI5
          dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true -o Grati

     - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            SRC/PhoneAgenda/PhoneAgendaWebAPI5/Grati
            
